"""initial_tables

Revision ID: 87683084116d
Revises: 
Create Date: 2026-03-17 17:31:15.156125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87683084116d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitigation_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('env', sa.String(length=16), nullable=False),
    sa.Column('analyst_email', sa.String(length=256), nullable=False),
    sa.Column('analyst_role', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_identifier', sa.String(length=512), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mitigation_audit_analyst', 'mitigation_audit_logs', ['analyst_email', 'created_at'], unique=False)
    op.create_index('ix_mitigation_audit_env_action', 'mitigation_audit_logs', ['env', 'action_type'], unique=False)
    op.create_index('ix_mitigation_audit_jsonb', 'mitigation_audit_logs', ['details'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_mitigation_audit_logs_action_type'), 'mitigation_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_mitigation_audit_logs_analyst_email'), 'mitigation_audit_logs', ['analyst_email'], unique=False)
    op.create_index(op.f('ix_mitigation_audit_logs_created_at'), 'mitigation_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_mitigation_audit_logs_env'), 'mitigation_audit_logs', ['env'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.alter_column('alerts', 'timestamp_label',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index('ix_alerts_event_id', table_name='alerts')
    op.drop_index('ix_alerts_line_id', table_name='alerts')
    op.drop_index('ix_alerts_source_ip', table_name='alerts')
    op.drop_index('ix_alerts_target_app', table_name='alerts')
    op.drop_index('ix_alerts_alert_id', table_name='alerts')
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.drop_column('alerts', 'timestamp')
    op.drop_column('alerts', 'component')
    op.drop_column('alerts', 'event_id')
    op.drop_column('alerts', 'level')
    op.drop_column('alerts', 'content')
    op.drop_column('alerts', 'source_ip')
    op.drop_column('alerts', 'target_app')
    op.drop_column('alerts', 'event_template')
    op.drop_column('alerts', 'line_id')
    op.alter_column('api_logs', 'app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('api_logs', 'target_app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('api_logs', 'source_ip',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('api_logs', 'action',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('api_logs', 'calls_today',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('api_logs', 'blocked_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('api_logs', 'actual_calls',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('api_logs', 'predicted_calls',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('api_logs', 'component',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_api_logs_env_ts', table_name='api_logs')
    op.drop_index('ix_api_logs_jsonb', table_name='api_logs', postgresql_using='gin')
    op.drop_index('ix_api_logs_line_id', table_name='api_logs')
    op.drop_index('ix_api_logs_source_ip', table_name='api_logs')
    op.drop_index('ix_api_logs_target_app', table_name='api_logs')
    op.create_index('ix_api_logs_env_action', 'api_logs', ['env', 'action'], unique=False)
    op.create_index('ix_api_logs_env_severity', 'api_logs', ['env', 'severity'], unique=False)
    op.alter_column('db_activity_logs', 'app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'target_app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'select_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'insert_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'update_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'delete_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'component',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_db_activity_logs_line_id', table_name='db_activity_logs')
    op.drop_index('ix_db_activity_logs_target_app', table_name='db_activity_logs')
    op.drop_index('ix_db_logs_env_suspicious', table_name='db_activity_logs')
    op.drop_index('ix_db_logs_env_ts', table_name='db_activity_logs')
    op.drop_index('ix_db_logs_jsonb', table_name='db_activity_logs', postgresql_using='gin')
    op.create_index('ix_db_activity_logs_env_severity', 'db_activity_logs', ['env', 'severity'], unique=False)
    op.create_index('ix_db_activity_logs_env_suspicious', 'db_activity_logs', ['env', 'is_suspicious'], unique=False)
    op.alter_column('endpoint_logs', 'employee',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('endpoint_logs', 'avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('endpoint_logs', 'target_app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('endpoint_logs', 'component',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_endpoint_logs_env_ts', table_name='endpoint_logs')
    op.drop_index('ix_endpoint_logs_jsonb', table_name='endpoint_logs', postgresql_using='gin')
    op.drop_index('ix_endpoint_logs_line_id', table_name='endpoint_logs')
    op.drop_index('ix_endpoint_logs_target_app', table_name='endpoint_logs')
    op.drop_index('ix_endpoint_logs_workstation_id', table_name='endpoint_logs')
    op.create_index('ix_endpoint_logs_env_malware', 'endpoint_logs', ['env', 'is_malware'], unique=False)
    op.create_index(op.f('ix_endpoint_logs_severity'), 'endpoint_logs', ['severity'], unique=False)
    op.create_index('ix_endpoint_logs_workstation', 'endpoint_logs', ['workstation_id'], unique=False)
    op.add_column('incidents', sa.Column('resolved_at', sa.String(length=64), nullable=True))
    op.alter_column('network_logs', 'app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('network_logs', 'target_app',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('network_logs', 'active_connections',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('network_logs', 'dropped_packets',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('network_logs', 'component',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_network_logs_env_ts', table_name='network_logs')
    op.drop_index('ix_network_logs_jsonb', table_name='network_logs', postgresql_using='gin')
    op.drop_index('ix_network_logs_line_id', table_name='network_logs')
    op.create_index('ix_network_logs_env_severity', 'network_logs', ['env', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_network_logs_env_severity', table_name='network_logs')
    op.create_index('ix_network_logs_line_id', 'network_logs', ['line_id'], unique=False)
    op.create_index('ix_network_logs_jsonb', 'network_logs', ['raw_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_network_logs_env_ts', 'network_logs', ['env', 'timestamp'], unique=False)
    op.alter_column('network_logs', 'component',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('network_logs', 'dropped_packets',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('network_logs', 'active_connections',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('network_logs', 'target_app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('network_logs', 'app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('incidents', 'resolved_at')
    op.drop_index('ix_endpoint_logs_workstation', table_name='endpoint_logs')
    op.drop_index(op.f('ix_endpoint_logs_severity'), table_name='endpoint_logs')
    op.drop_index('ix_endpoint_logs_env_malware', table_name='endpoint_logs')
    op.create_index('ix_endpoint_logs_workstation_id', 'endpoint_logs', ['workstation_id'], unique=False)
    op.create_index('ix_endpoint_logs_target_app', 'endpoint_logs', ['target_app'], unique=False)
    op.create_index('ix_endpoint_logs_line_id', 'endpoint_logs', ['line_id'], unique=False)
    op.create_index('ix_endpoint_logs_jsonb', 'endpoint_logs', ['raw_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_endpoint_logs_env_ts', 'endpoint_logs', ['env', 'timestamp'], unique=False)
    op.alter_column('endpoint_logs', 'component',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('endpoint_logs', 'target_app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('endpoint_logs', 'avatar',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('endpoint_logs', 'employee',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_index('ix_db_activity_logs_env_suspicious', table_name='db_activity_logs')
    op.drop_index('ix_db_activity_logs_env_severity', table_name='db_activity_logs')
    op.create_index('ix_db_logs_jsonb', 'db_activity_logs', ['raw_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_db_logs_env_ts', 'db_activity_logs', ['env', 'timestamp'], unique=False)
    op.create_index('ix_db_logs_env_suspicious', 'db_activity_logs', ['env', 'is_suspicious'], unique=False)
    op.create_index('ix_db_activity_logs_target_app', 'db_activity_logs', ['target_app'], unique=False)
    op.create_index('ix_db_activity_logs_line_id', 'db_activity_logs', ['line_id'], unique=False)
    op.alter_column('db_activity_logs', 'component',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('db_activity_logs', 'delete_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'update_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'insert_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'select_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'target_app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('db_activity_logs', 'app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_index('ix_api_logs_env_severity', table_name='api_logs')
    op.drop_index('ix_api_logs_env_action', table_name='api_logs')
    op.create_index('ix_api_logs_target_app', 'api_logs', ['target_app'], unique=False)
    op.create_index('ix_api_logs_source_ip', 'api_logs', ['source_ip'], unique=False)
    op.create_index('ix_api_logs_line_id', 'api_logs', ['line_id'], unique=False)
    op.create_index('ix_api_logs_jsonb', 'api_logs', ['raw_payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_api_logs_env_ts', 'api_logs', ['env', 'timestamp'], unique=False)
    op.alter_column('api_logs', 'component',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('api_logs', 'predicted_calls',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('api_logs', 'actual_calls',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('api_logs', 'blocked_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('api_logs', 'calls_today',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('api_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('api_logs', 'source_ip',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('api_logs', 'target_app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('api_logs', 'app',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.add_column('alerts', sa.Column('line_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('event_template', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('target_app', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('source_ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('level', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('component', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('timestamp', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.create_index('ix_alerts_alert_id', 'alerts', ['alert_id'], unique=True)
    op.create_index('ix_alerts_target_app', 'alerts', ['target_app'], unique=False)
    op.create_index('ix_alerts_source_ip', 'alerts', ['source_ip'], unique=False)
    op.create_index('ix_alerts_line_id', 'alerts', ['line_id'], unique=False)
    op.create_index('ix_alerts_event_id', 'alerts', ['event_id'], unique=False)
    op.alter_column('alerts', 'timestamp_label',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Deactivated accounts cannot log in but retain audit history'),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Updated on every successful authentication'),
    sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False, comment='Reset to 0 on success; used for account lockout policy'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_mitigation_audit_logs_env'), table_name='mitigation_audit_logs')
    op.drop_index(op.f('ix_mitigation_audit_logs_created_at'), table_name='mitigation_audit_logs')
    op.drop_index(op.f('ix_mitigation_audit_logs_analyst_email'), table_name='mitigation_audit_logs')
    op.drop_index(op.f('ix_mitigation_audit_logs_action_type'), table_name='mitigation_audit_logs')
    op.drop_index('ix_mitigation_audit_jsonb', table_name='mitigation_audit_logs', postgresql_using='gin')
    op.drop_index('ix_mitigation_audit_env_action', table_name='mitigation_audit_logs')
    op.drop_index('ix_mitigation_audit_analyst', table_name='mitigation_audit_logs')
    op.drop_table('mitigation_audit_logs')
    # ### end Alembic commands ###
